### ISSUE TITLE
logicaldefinition axioms

### ISSUE THREAD

**Issue by cmungall** [biodatamodels/obograph#1]
E.g. https://raw.githubusercontent.com/julesjacobsen/obographs/immutables/examples/hp.yaml

```yaml
  logicalDefinitionAxioms:
  - definedClassId: "http://purl.obolibrary.org/obo/CL_0000005"
    genusIds:
    - "http://purl.obolibrary.org/obo/CL_0000057"
    restrictions:
    - propertyId: "http://purl.obolibrary.org/obo/RO_0002202"
      fillerId: "http://purl.obolibrary.org/obo/CL_0000333"
  - definedClassId: "http://purl.obolibrary.org/obo/CL_0000014"
    genusIds:
    - "http://purl.obolibrary.org/obo/CL_0000039"
    restrictions:
    - propertyId: "http://purl.obolibrary.org/obo/RO_0002215"
      fillerId: "http://purl.obolibrary.org/obo/GO_0017145"
```

We also need to say the min length of the restrictions like is 1, may require linkml extension, see 
https://github.com/geneontology/obographs/issues/75
